# Generated by Django 3.2.7 on 2021-09-02 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='quantity',
            field=models.CharField(max_length=250),
        ),
    ]
